name: Publish to internal registry
on:
  push:
    branches:
      - forked_main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Authenticate with github npm repository
        run: |
          npm set "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}"
          npm set @mccare:registry=https://npm.pkg.github.com

      - name: Install dependencies
        run: pnpm install

      - name: Build package
        run: |
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --global user.name "Github Action"
          pnpm version --no-git-tag-version patch
          pnpm build

      - name: Deploy Package to NPM
        run: |
          pnpm publish --no-git-checks
          currentVersion=$(jq -r '.version' < package.json)
          git commit -am "Update to $currentVersion"
          git push
